### ISSUE TITLE
Not an real issue, but question about damage!

### ISSUE THREAD

**Issue by Djurres** [anthonynguyen/ioq3-for-UrbanTerror-4#5]
Hello Anthony,

So far, i'm running your mod which is running clean as fuck. Thanks for that, but now I would love to change some weapondamage and how quick some weapons fire. Is there any possibility I can edit it by myself? I couldn't find out where to edit the source.

Compiling the file won't be the problem at all, thats what i already have done.

Thanks for this release, works perfectly!
Thx in advance!

**Comment by danielepantaleone** [comment]
Weapons are defined in the game QVM and not in the engine. Technically from the engine you can access the QVM memory and change some stuff but (1) it's not that of an easy task and (2) you should not mod a game in the first place unless the developers authorize game modifications. One thing is patching an engine to introduces fixes and improvements, another thing is changing the gameplay.

**Comment by Djurres** [comment]
Hey Daniel!

Thanks for your quick response!

I thought it could've been modded into the i386, but since its fixed in the QVM's i'm not gonna try to edit then. No fall dmg and unlimited wj's are enough so far!

Thanks again :)

**Comment by anthonynguyen** [comment]
👍
